export interface Service {
  id: string
  slug: string
  name: string
  category: string
}

export interface CountryPrice {
  iso: string
  code: string
  name: string
  phonePrefix: string
  priceUsd: number
  priceXaf: number
  flag: string
}

export function usdToXaf(priceUsd: number): number {
  const rate = 655.957
  const baseXaf = Math.ceil(priceUsd * rate)
  let margin: number
  if (priceUsd < 0.5) margin = 500
  else if (priceUsd <= 1) margin = 1000
  else margin = 2000
  return baseXaf + margin
}

export const SERVICES: Service[] = [
  { id: 'wa', slug: 'whatsapp', name: 'Whatsapp', category: 'social' },
  { id: 'li', slug: 'baidu', name: 'Baidu', category: 'social' },
  { id: 'ds', slug: 'discord', name: 'Discord', category: 'social' },
  { id: 'fb', slug: 'facebook', name: 'Facebook', category: 'social' },
  { id: 'im', slug: 'imo', name: 'Imo', category: 'social' },
  { id: 'ig', slug: 'instagram', name: 'Instagram', category: 'social' },
  { id: 'me', slug: 'line-messenger', name: 'Line messenger', category: 'social' },
  { id: 'bw', slug: 'signal', name: 'Signal', category: 'social' },
  { id: 'fu', slug: 'snapchat', name: 'Snapchat', category: 'social' },
  { id: 'tg', slug: 'telegram', name: 'Telegram', category: 'social' },
  { id: 'tw', slug: 'twitter', name: 'Twitter', category: 'social' },
  { id: 'vi', slug: 'viber', name: 'Viber', category: 'social' },
  { id: 'tt', slug: 'ziglu', name: 'Ziglu', category: 'social' },
  { id: 'vb', slug: 'vb', name: 'Кораблик', category: 'social' },
  { id: 'ab', slug: 'alibaba', name: 'Alibaba', category: 'ecommerce' },
  { id: 'hx', slug: 'aliexpress', name: 'Aliexpress', category: 'ecommerce' },
  { id: 'hw', slug: 'alipay-alibaba-1688', name: 'Alipay/alibaba/1688', category: 'ecommerce' },
  { id: 'yn', slug: 'allegro', name: 'Allegro', category: 'ecommerce' },
  { id: 'xt', slug: 'flipkart', name: 'Flipkart', category: 'ecommerce' },
  { id: 'jd', slug: 'girabank', name: 'Girabank', category: 'ecommerce' },
  { id: 'za', slug: 'jdcom', name: 'Jdcom', category: 'ecommerce' },
  { id: 'dl', slug: 'lazada', name: 'Lazada', category: 'ecommerce' },
  { id: 'sn', slug: 'olx', name: 'Olx', category: 'ecommerce' },
  { id: 'ka', slug: 'shopee', name: 'Shopee', category: 'ecommerce' },
  { id: 'pr', slug: 'trendyol', name: 'Trendyol', category: 'ecommerce' },
  { id: 'uu', slug: 'wildberries', name: 'Wildberries', category: 'ecommerce' },
  { id: 'ua', slug: 'blablacar', name: 'Blablacar', category: 'delivery' },
  { id: 'tx', slug: 'bolt', name: 'Bolt', category: 'delivery' },
  { id: 'dt', slug: 'delivery-club', name: 'Delivery club', category: 'delivery' },
  { id: 'ul', slug: 'getir', name: 'Getir', category: 'delivery' },
  { id: 'ni', slug: 'gojek', name: 'Gojek', category: 'delivery' },
  { id: 'jg', slug: 'grab', name: 'Grab', category: 'delivery' },
  { id: 'tu', slug: 'lyft', name: 'Lyft', category: 'delivery' },
  { id: 'ub', slug: 'uber', name: 'Uber', category: 'delivery' },
  { id: 'rr', slug: 'wolt', name: 'Wolt', category: 'delivery' },
  { id: 're', slug: 'coinbase', name: 'Coinbase', category: 'finance' },
  { id: 'ti', slug: 'cryptocom', name: 'Cryptocom', category: 'finance' },
  { id: 'ts', slug: 'paypal', name: 'Paypal', category: 'finance' },
  { id: 'ge', slug: 'paytm', name: 'Paytm', category: 'finance' },
  { id: 'ij', slug: 'revolut', name: 'Revolut', category: 'finance' },
  { id: 'nu', slug: 'stripe', name: 'Stripe', category: 'finance' },
  { id: 'bo', slug: 'wise', name: 'Wise', category: 'finance' },
  { id: 'qv', slug: 'badoo', name: 'Badoo', category: 'dating' },
  { id: 'mo', slug: 'bumble', name: 'Bumble', category: 'dating' },
  { id: 'ir', slug: 'chispa', name: 'Chispa', category: 'dating' },
  { id: 'mv', slug: 'fruitz', name: 'Fruitz', category: 'dating' },
  { id: 'vz', slug: 'hinge', name: 'Hinge', category: 'dating' },
  { id: 'oi', slug: 'tinder', name: 'Tinder', category: 'dating' },
  { id: 'pp', slug: 'huya', name: 'Huya', category: 'streaming' },
  { id: 'nf', slug: 'netflix', name: 'Netflix', category: 'streaming' },
  { id: 'hb', slug: 'twitch', name: 'Twitch', category: 'streaming' },
  { id: 'bz', slug: 'blizzard', name: 'Blizzard', category: 'gaming' },
  { id: 'mt', slug: 'steam', name: 'Steam', category: 'gaming' },
  { id: 'wx', slug: 'apple', name: 'Apple', category: 'professional' },
  { id: 'go', slug: 'google-youtube-gmail', name: 'Google,youtube,gmail', category: 'professional' },
  { id: 'tn', slug: 'linkedin', name: 'Linkedin', category: 'professional' },
  { id: 'mm', slug: 'microsoft', name: 'Microsoft', category: 'professional' },
  { id: 'dr', slug: 'openai', name: 'Openai', category: 'professional' },
  { id: 'wp', slug: '163-om', name: '163сom', category: 'other' },
  { id: 'hn', slug: '1688', name: '1688', category: 'other' },
  { id: 'wj', slug: '1-bet', name: '1хbet', category: 'other' },
  { id: 'lh', slug: '24betting', name: '24betting', category: 'other' },
  { id: 'qi', slug: '32red', name: '32red', category: 'other' },
  { id: 'hk', slug: '4fun', name: '4fun', category: 'other' },
  { id: 'll', slug: '888casino', name: '888casino', category: 'other' },
  { id: 'fw', slug: '99acres', name: '99acres', category: 'other' },
  { id: 'ki', slug: '99app', name: '99app', category: 'other' },
  { id: 'gn', slug: 'a9a', name: 'A9a', category: 'other' },
  { id: 'rh', slug: 'ace2three', name: 'Ace2three', category: 'other' },
  { id: 'ko', slug: 'adakami', name: 'Adakami', category: 'other' },
  { id: 'bq', slug: 'adani', name: 'Adani', category: 'other' },
  { id: 'an', slug: 'adidas', name: 'Adidas', category: 'other' },
  { id: 'sa', slug: 'agibank', name: 'Agibank', category: 'other' },
  { id: 'cs', slug: 'agridevelop', name: 'Agridevelop', category: 'other' },
  { id: 'qu', slug: 'agroinform', name: 'Agroinform', category: 'other' },
  { id: 'uk', slug: 'airbnb', name: 'Airbnb', category: 'other' },
  { id: 'zl', slug: 'airtel', name: 'Airtel', category: 'other' },
  { id: 'wv', slug: 'ais', name: 'Ais', category: 'other' },
  { id: 'jj', slug: 'aitu', name: 'Aitu', category: 'other' },
  { id: 'rf', slug: 'akudo', name: 'Akudo', category: 'other' },
  { id: 'tm', slug: 'akulaku', name: 'Akulaku', category: 'other' },
  { id: 'bt', slug: 'alfa', name: 'Alfa', category: 'other' },
  { id: 'bn', slug: 'alfagift', name: 'Alfagift', category: 'other' },
  { id: 'lp', slug: 'algida', name: 'Algida', category: 'other' },
  { id: 'nh', slug: 'allobank', name: 'Allobank', category: 'other' },
  { id: 'yo', slug: 'amasia', name: 'Amasia', category: 'other' },
  { id: 'am', slug: 'amazon', name: 'Amazon', category: 'other' },
  { id: 'pm', slug: 'aol', name: 'Aol', category: 'other' },
  { id: 'ml', slug: 'apostaganha', name: 'Apostaganha', category: 'other' },
  { id: 'gk', slug: 'aptekaru', name: 'Aptekaru', category: 'other' },
  { id: 'rq', slug: 'aptekiplus', name: 'Aptekiplus', category: 'other' },
  { id: 'hs', slug: 'asda', name: 'Asda', category: 'other' },
  { id: 'gr', slug: 'astropay', name: 'Astropay', category: 'other' },
  { id: 'du', slug: 'aubank', name: 'Aubank', category: 'other' },
  { id: 'kd', slug: 'author24', name: 'Author24', category: 'other' },
  { id: 'av', slug: 'avito', name: 'Avito', category: 'other' },
  { id: 'ff', slug: 'avon', name: 'Avon', category: 'other' },
  { id: 'hl', slug: 'band', name: 'Band', category: 'other' },
  { id: 'vc', slug: 'banqi', name: 'Banqi', category: 'other' },
  { id: 'cb', slug: 'bazos', name: 'Bazos', category: 'other' },
  { id: 'ov', slug: 'beget', name: 'Beget', category: 'other' },
  { id: 'um', slug: 'belwest', name: 'Belwest', category: 'other' },
  { id: 'ck', slug: 'bereal', name: 'Bereal', category: 'other' },
  { id: 'ie', slug: 'bet365', name: 'Bet365', category: 'other' },
  { id: 'vd', slug: 'betfair', name: 'Betfair', category: 'other' },
  { id: 'zn', slug: 'biedronka', name: 'Biedronka', category: 'other' },
  { id: 'zu', slug: 'bigc', name: 'Bigc', category: 'other' },
  { id: 'bl', slug: 'bigo-live', name: 'Bigo live', category: 'other' },
  { id: 'zs', slug: 'bilibili', name: 'Bilibili', category: 'other' },
  { id: 'ri', slug: 'billmill', name: 'Billmill', category: 'other' },
  { id: 'uv', slug: 'binbin', name: 'Binbin', category: 'other' },
  { id: 'ww', slug: 'bip', name: 'Bip', category: 'other' },
  { id: 'el', slug: 'bisu', name: 'Bisu', category: 'other' },
  { id: 'qk', slug: 'bit', name: 'Bit', category: 'other' },
  { id: 'pt', slug: 'bitaqaty', name: 'Bitaqaty', category: 'other' },
  { id: 'lt', slug: 'bitclout', name: 'Bitclout', category: 'other' },
  { id: 'ht', slug: 'bitso', name: 'Bitso', category: 'other' },
  { id: 'fk', slug: 'blibli', name: 'Blibli', category: 'other' },
  { id: 'rw', slug: 'bls-spain', name: 'Bls-spain', category: 'other' },
  { id: 'qn', slug: 'blued', name: 'Blued', category: 'other' },
  { id: 'jw', slug: 'br777', name: 'Br777', category: 'other' },
  { id: 'sy', slug: 'brahma', name: 'Brahma', category: 'other' },
  { id: 'vo', slug: 'brand20ua', name: 'Brand20ua', category: 'other' },
  { id: 'vt', slug: 'budget4me', name: 'Budget4me', category: 'other' },
  { id: 'zt', slug: 'budweiser', name: 'Budweiser', category: 'other' },
  { id: 'kh', slug: 'bukalapak', name: 'Bukalapak', category: 'other' },
  { id: 'ip', slug: 'burger-king', name: 'Burger king', category: 'other' },
  { id: 'iu', slug: 'bykea', name: 'Bykea', category: 'other' },
  { id: 'uo', slug: 'cafebazaar', name: 'Cafebazaar', category: 'other' },
  { id: 'my', slug: 'caixa', name: 'Caixa', category: 'other' },
  { id: 'gw', slug: 'callapp', name: 'Callapp', category: 'other' },
  { id: 'ls', slug: 'careem', name: 'Careem', category: 'other' },
  { id: 'gj', slug: 'carousell', name: 'Carousell', category: 'other' },
  { id: 'it', slug: 'cashapp', name: 'Cashapp', category: 'other' },
  { id: 'oy', slug: 'cashfly', name: 'Cashfly', category: 'other' },
  { id: 'ii', slug: 'cashkaro', name: 'Cashkaro', category: 'other' },
  { id: 'ld', slug: 'cashmine', name: 'Cashmine', category: 'other' },
  { id: 'pc', slug: 'casino-bet-gambling', name: 'Casino/bet/gambling', category: 'other' },
  { id: 'wd', slug: 'casinoplus', name: 'Casinoplus', category: 'other' },
  { id: 'ho', slug: 'cathay', name: 'Cathay', category: 'other' },
  { id: 'pq', slug: 'cdkeys', name: 'Cdkeys', category: 'other' },
  { id: 'ix', slug: 'celcoin', name: 'Celcoin', category: 'other' },
  { id: 'ai', slug: 'celebe', name: 'Celebe', category: 'other' },
  { id: 'td', slug: 'chaingefinance', name: 'Chaingefinance', category: 'other' },
  { id: 'si', slug: 'cita-previa', name: 'Cita previa', category: 'other' },
  { id: 'az', slug: 'citybase', name: 'Citybase', category: 'other' },
  { id: 'yf', slug: 'citymobil', name: 'Citymobil', category: 'other' },
  { id: 'hf', slug: 'cleartrip', name: 'Cleartrip', category: 'other' },
  { id: 'fe', slug: 'cliqq', name: 'Cliqq', category: 'other' },
  { id: 'jn', slug: 'cloudbet', name: 'Cloudbet', category: 'other' },
  { id: 'dd', slug: 'cloudchat', name: 'Cloudchat', category: 'other' },
  { id: 'et', slug: 'clubhouse', name: 'Clubhouse', category: 'other' },
  { id: 'ql', slug: 'cmtcuzdan', name: 'Cmtcuzdan', category: 'other' },
  { id: 'oe', slug: 'codashop', name: 'Codashop', category: 'other' },
  { id: 'pn', slug: 'coffeelike', name: 'Coffeelike', category: 'other' },
  { id: 'ne', slug: 'coindcx', name: 'Coindcx', category: 'other' },
  { id: 'vw', slug: 'coinfield', name: 'Coinfield', category: 'other' },
  { id: 'zx', slug: 'communitygaming', name: 'Communitygaming', category: 'other' },
  { id: 'jv', slug: 'consultant', name: 'Consultant', category: 'other' },
  { id: 'eg', slug: 'contactsys', name: 'Contactsys', category: 'other' },
  { id: 'om', slug: 'corona', name: 'Corona', category: 'other' },
  { id: 'yg', slug: 'coursehero', name: 'Coursehero', category: 'other' },
  { id: 'wc', slug: 'craigslist', name: 'Craigslist', category: 'other' },
  { id: 'ax', slug: 'crefisamais', name: 'Crefisamais', category: 'other' },
  { id: 'lu', slug: 'crickpe', name: 'Crickpe', category: 'other' },
  { id: 'sx', slug: 'crowdtap', name: 'Crowdtap', category: 'other' },
  { id: 'ox', slug: 'damejidlo', name: 'Damejidlo', category: 'other' },
  { id: 'fr', slug: 'dana', name: 'Dana', category: 'other' },
  { id: 'tj', slug: 'dbrua', name: 'Dbrua', category: 'other' },
  { id: 'oc', slug: 'dealshare', name: 'Dealshare', category: 'other' },
  { id: 'zk', slug: 'deliveroo', name: 'Deliveroo', category: 'other' },
  { id: 'zz', slug: 'dent', name: 'Dent', category: 'other' },
  { id: 'xy', slug: 'depop', name: 'Depop', category: 'other' },
  { id: 'lx', slug: 'dewupoison', name: 'Dewupoison', category: 'other' },
  { id: 'os', slug: 'dhani', name: 'Dhani', category: 'other' },
  { id: 'xk', slug: 'didi', name: 'Didi', category: 'other' },
  { id: 'zv', slug: 'digikala', name: 'Digikala', category: 'other' },
  { id: 'ud', slug: 'disney-hotstar', name: 'Disney hotstar', category: 'other' },
  { id: 'dw', slug: 'divar', name: 'Divar', category: 'other' },
  { id: 'sd', slug: 'dodopizza', name: 'Dodopizza', category: 'other' },
  { id: 'dz', slug: 'dominos-pizza', name: 'Dominos pizza', category: 'other' },
  { id: 'ac', slug: 'doordash', name: 'Doordash', category: 'other' },
  { id: 'bx', slug: 'dosi', name: 'Dosi', category: 'other' },
  { id: 'sv', slug: 'dostavista', name: 'Dostavista', category: 'other' },
  { id: 'cj', slug: 'dotz', name: 'Dotz', category: 'other' },
  { id: 'ak', slug: 'douyu', name: 'Douyu', category: 'other' },
  { id: 've', slug: 'dream11', name: 'Dream11', category: 'other' },
  { id: 'hz', slug: 'drom', name: 'Drom', category: 'other' },
  { id: 'fi', slug: 'dundle', name: 'Dundle', category: 'other' },
  { id: 'le', slug: 'e-bike-gewinnspiel', name: 'E bike gewinnspiel', category: 'other' },
  { id: 'rz', slug: 'easypay', name: 'Easypay', category: 'other' },
  { id: 'dh', slug: 'ebay', name: 'Ebay', category: 'other' },
  { id: 'te', slug: 'efood', name: 'Efood', category: 'other' },
  { id: 'uf', slug: 'eneba', name: 'Eneba', category: 'other' },
  { id: 'ah', slug: 'escapefromtarkov', name: 'Escapefromtarkov', category: 'other' },
  { id: 'yj', slug: 'ewallet', name: 'Ewallet', category: 'other' },
  { id: 'ba', slug: 'expressmoney', name: 'Expressmoney', category: 'other' },
  { id: 'kr', slug: 'eyecon', name: 'Eyecon', category: 'other' },
  { id: 'db', slug: 'ezbuy', name: 'Ezbuy', category: 'other' },
  { id: 'rm', slug: 'faberlic', name: 'Faberlic', category: 'other' },
  { id: 'qz', slug: 'faceit', name: 'Faceit', category: 'other' },
  { id: 'xn', slug: 'familia', name: 'Familia', category: 'other' },
  { id: 'lm', slug: 'farpost', name: 'Farpost', category: 'other' },
  { id: 'mr', slug: 'fastmail', name: 'Fastmail', category: 'other' },
  { id: 'se', slug: 'feeld', name: 'Feeld', category: 'other' },
  { id: 'ug', slug: 'fiqsy', name: 'Fiqsy', category: 'other' },
  { id: 'cn', slug: 'fiverr', name: 'Fiverr', category: 'other' },
  { id: 'tv', slug: 'flink', name: 'Flink', category: 'other' },
  { id: 'iy', slug: 'foodhub', name: 'Foodhub', category: 'other' },
  { id: 'nz', slug: 'foodpanda', name: 'Foodpanda', category: 'other' },
  { id: 'kw', slug: 'foody', name: 'Foody', category: 'other' },
  { id: 'gu', slug: 'fora', name: 'Fora', category: 'other' },
  { id: 'xg', slug: 'fortunask', name: 'Fortunask', category: 'other' },
  { id: 'rk', slug: 'fotka', name: 'Fotka', category: 'other' },
  { id: 'kq', slug: 'fotocasa', name: 'Fotocasa', category: 'other' },
  { id: 'wz', slug: 'foxford', name: 'Foxford', category: 'other' },
  { id: 'kg', slug: 'freechargeapp', name: 'Freechargeapp', category: 'other' },
  { id: 'gq', slug: 'freelancer', name: 'Freelancer', category: 'other' },
  { id: 'zb', slug: 'freenow', name: 'Freenow', category: 'other' },
  { id: 'nj', slug: 'freshkarta', name: 'Freshkarta', category: 'other' },
  { id: 'ng', slug: 'funpay', name: 'Funpay', category: 'other' },
  { id: 'od', slug: 'fwdmax', name: 'Fwdmax', category: 'other' },
  { id: 'bk', slug: 'g2g', name: 'G2g', category: 'other' },
  { id: 'ou', slug: 'gabi', name: 'Gabi', category: 'other' },
  { id: 'xe', slug: 'galaxychat', name: 'Galaxychat', category: 'other' },
  { id: 'af', slug: 'galaxywin', name: 'Galaxywin', category: 'other' },
  { id: 'wn', slug: 'gamearena', name: 'Gamearena', category: 'other' },
  { id: 'pa', slug: 'gamekit', name: 'Gamekit', category: 'other' },
  { id: 'ed', slug: 'gamer', name: 'Gamer', category: 'other' },
  { id: 'bc', slug: 'gcash', name: 'Gcash', category: 'other' },
  { id: 'cg', slug: 'gemgala', name: 'Gemgala', category: 'other' },
  { id: 'cz', slug: 'getmega', name: 'Getmega', category: 'other' },
  { id: 'gt', slug: 'gett', name: 'Gett', category: 'other' },
  { id: 'qe', slug: 'gg', name: 'Gg', category: 'other' },
  { id: 'nn', slug: 'giftcloud', name: 'Giftcloud', category: 'other' },
  { id: 'nk', slug: 'gittigidiyor', name: 'Gittigidiyor', category: 'other' },
  { id: 'iz', slug: 'global24', name: 'Global24', category: 'other' },
  { id: 'gl', slug: 'globaltel', name: 'Globaltel', category: 'other' },
  { id: 'hm', slug: 'globus', name: 'Globus', category: 'other' },
  { id: 'aq', slug: 'glovo', name: 'Glovo', category: 'other' },
  { id: 'mq', slug: 'gmng', name: 'Gmng', category: 'other' },
  { id: 'ez', slug: 'goerlifaucet', name: 'Goerlifaucet', category: 'other' },
  { id: 'bp', slug: 'gofundme', name: 'Gofundme', category: 'other' },
  { id: 'gf', slug: 'googlevoice', name: 'Googlevoice', category: 'other' },
  { id: 'yw', slug: 'grindr', name: 'Grindr', category: 'other' },
  { id: 'ln', slug: 'grofers', name: 'Grofers', category: 'other' },
  { id: 'xs', slug: 'groupme', name: 'Groupme', category: 'other' },
  { id: 'ik', slug: 'gurubets', name: 'Gurubets', category: 'other' },
  { id: 'gh', slug: 'gyftr', name: 'Gyftr', category: 'other' },
  { id: 'rp', slug: 'hamrahaval', name: 'Hamrahaval', category: 'other' },
  { id: 'sj', slug: 'handypick', name: 'Handypick', category: 'other' },
  { id: 'df', slug: 'happn', name: 'Happn', category: 'other' },
  { id: 'sp', slug: 'happyfresh', name: 'Happyfresh', category: 'other' },
  { id: 'au', slug: 'haraj', name: 'Haraj', category: 'other' },
  { id: 'gx', slug: 'hepsiburadacom', name: 'Hepsiburadacom', category: 'other' },
  { id: 'en', slug: 'hermes', name: 'Hermes', category: 'other' },
  { id: 'vx', slug: 'heybox', name: 'Heybox', category: 'other' },
  { id: 'ss', slug: 'hezzl', name: 'Hezzl', category: 'other' },
  { id: 'yh', slug: 'hh', name: 'Hh', category: 'other' },
  { id: 'rt', slug: 'hily', name: 'Hily', category: 'other' },
  { id: 'ks', slug: 'hirect', name: 'Hirect', category: 'other' },
  { id: 'ru', slug: 'hop', name: 'Hop', category: 'other' },
  { id: 'jl', slug: 'hopi', name: 'Hopi', category: 'other' },
  { id: 'gi', slug: 'hotline', name: 'Hotline', category: 'other' },
  { id: 'kp', slug: 'hq-trivia', name: 'Hq trivia', category: 'other' },
  { id: 'un', slug: 'humblebundle', name: 'Humblebundle', category: 'other' },
  { id: 'gv', slug: 'humta', name: 'Humta', category: 'other' },
  { id: 'dq', slug: 'icecasino', name: 'Icecasino', category: 'other' },
  { id: 'iq', slug: 'icq', name: 'Icq', category: 'other' },
  { id: 'cx', slug: 'icrypex', name: 'Icrypex', category: 'other' },
  { id: 'kk', slug: 'idealista', name: 'Idealista', category: 'other' },
  { id: 'pd', slug: 'ifood', name: 'Ifood', category: 'other' },
  { id: 'ib', slug: 'immowelt', name: 'Immowelt', category: 'other' },
  { id: 'iv', slug: 'inboxlv', name: 'Inboxlv', category: 'other' },
  { id: 'tp', slug: 'indiagold', name: 'Indiagold', category: 'other' },
  { id: 'fg', slug: 'indianoil', name: 'Indianoil', category: 'other' },
  { id: 'zq', slug: 'indiaplays', name: 'Indiaplays', category: 'other' },
  { id: 'ws', slug: 'indodax', name: 'Indodax', category: 'other' },
  { id: 'ju', slug: 'indomaret', name: 'Indomaret', category: 'other' },
  { id: 'rl', slug: 'indriver', name: 'Indriver', category: 'other' },
  { id: 'xi', slug: 'infund', name: 'Infund', category: 'other' },
  { id: 'hy', slug: 'ininal', name: 'Ininal', category: 'other' },
  { id: 'yv', slug: 'iplwin', name: 'Iplwin', category: 'other' },
  { id: 'es', slug: 'iqiyi', name: 'Iqiyi', category: 'other' },
  { id: 'il', slug: 'iqos', name: 'Iqos', category: 'other' },
  { id: 'cf', slug: 'irancell', name: 'Irancell', category: 'other' },
  { id: 'us', slug: 'irctc', name: 'Irctc', category: 'other' },
  { id: 'ad', slug: 'iti', name: 'Iti', category: 'other' },
  { id: 'jc', slug: 'ivi', name: 'Ivi', category: 'other' },
  { id: 'dm', slug: 'iwplay', name: 'Iwplay', category: 'other' },
  { id: 'wt', slug: 'izi', name: 'Izi', category: 'other' },
  { id: 'ea', slug: 'jamesdelivery', name: 'Jamesdelivery', category: 'other' },
  { id: 'hr', slug: 'jkf', name: 'Jkf', category: 'other' },
  { id: 'ic', slug: 'jogo', name: 'Jogo', category: 'other' },
  { id: 'xx', slug: 'joyride', name: 'Joyride', category: 'other' },
  { id: 'yx', slug: 'jtexpress', name: 'Jtexpress', category: 'other' },
  { id: 'hi', slug: 'jungleerummy', name: 'Jungleerummy', category: 'other' },
  { id: 'pu', slug: 'justdating', name: 'Justdating', category: 'other' },
  { id: 'zo', slug: 'kaggle', name: 'Kaggle', category: 'other' },
  { id: 'kt', slug: 'kakaotalk', name: 'Kakaotalk', category: 'other' },
  { id: 'de', slug: 'karusel', name: 'Karusel', category: 'other' },
  { id: 'jz', slug: 'kaya', name: 'Kaya', category: 'other' },
  { id: 'ol', slug: 'kazanexpress', name: 'Kazanexpress', category: 'other' },
  { id: 'bf', slug: 'keybase', name: 'Keybase', category: 'other' },
  { id: 'ra', slug: 'keypay', name: 'Keypay', category: 'other' },
  { id: 'fz', slug: 'kfc', name: 'Kfc', category: 'other' },
  { id: 'uw', slug: 'kirana', name: 'Kirana', category: 'other' },
  { id: 'kl', slug: 'kolesa-kz', name: 'Kolesa.kz', category: 'other' },
  { id: 'pv', slug: 'koshelek', name: 'Koshelek', category: 'other' },
  { id: 'rv', slug: 'kotak811', name: 'Kotak811', category: 'other' },
  { id: 'sq', slug: 'kucoinplay', name: 'Kucoinplay', category: 'other' },
  { id: 'kb', slug: 'kufarby', name: 'Kufarby', category: 'other' },
  { id: 'vp', slug: 'kwai', name: 'Kwai', category: 'other' },
  { id: 'er', slug: 'kwork', name: 'Kwork', category: 'other' },
  { id: 'vq', slug: 'ladymaria', name: 'Ladymaria', category: 'other' },
  { id: 'fh', slug: 'lalamove', name: 'Lalamove', category: 'other' },
  { id: 'sb', slug: 'lamoda', name: 'Lamoda', category: 'other' },
  { id: 'bb', slug: 'lazypay', name: 'Lazypay', category: 'other' },
  { id: 'do', slug: 'leboncoin', name: 'Leboncoin', category: 'other' },
  { id: 'wq', slug: 'leboncoin1', name: 'Leboncoin1', category: 'other' },
  { id: 'rd', slug: 'lenta', name: 'Lenta', category: 'other' },
  { id: 'pz', slug: 'lidl', name: 'Lidl', category: 'other' },
  { id: 'oo', slug: 'ligapro', name: 'Ligapro', category: 'other' },
  { id: 'xf', slug: 'lightchat', name: 'Lightchat', category: 'other' },
  { id: 'jf', slug: 'likee', name: 'Likee', category: 'other' },
  { id: 'ex', slug: 'linode', name: 'Linode', category: 'other' },
  { id: 'eu', slug: 'livescore', name: 'Livescore', category: 'other' },
  { id: 'di', slug: 'loanflix', name: 'Loanflix', category: 'other' },
  { id: 'su', slug: 'loco', name: 'Loco', category: 'other' },
  { id: 'mk', slug: 'longhu', name: 'Longhu', category: 'other' },
  { id: 'rs', slug: 'lotus', name: 'Lotus', category: 'other' },
  { id: 'zi', slug: 'lovelocal', name: 'Lovelocal', category: 'other' },
  { id: 'oj', slug: 'loveru', name: 'Loveru', category: 'other' },
  { id: 'dj', slug: 'lukoil-azs', name: 'Lukoil-azs', category: 'other' },
  { id: 'gz', slug: 'lyka', name: 'Lyka', category: 'other' },
  { id: 'hq', slug: 'magicbricks', name: 'Magicbricks', category: 'other' },
  { id: 'up', slug: 'magnolia', name: 'Magnolia', category: 'other' },
  { id: 'ma', slug: 'mail-ru', name: 'Mail.ru', category: 'other' },
  { id: 'lb', slug: 'mailru-group', name: 'Mailru group', category: 'other' },
  { id: 'fd', slug: 'mamba-meetme', name: 'Mamba, meetme', category: 'other' },
  { id: 'oh', slug: 'maplesea', name: 'Maplesea', category: 'other' },
  { id: 'bm', slug: 'marketguru', name: 'Marketguru', category: 'other' },
  { id: 'hd', slug: 'marketpapa', name: 'Marketpapa', category: 'other' },
  { id: 'ry', slug: 'mcdonalds', name: 'Mcdonalds', category: 'other' },
  { id: 'lg', slug: 'medibuddy', name: 'Medibuddy', category: 'other' },
  { id: 'hp', slug: 'meesho', name: 'Meesho', category: 'other' },
  { id: 'qr', slug: 'mega', name: 'Mega', category: 'other' },
  { id: 'lv', slug: 'megogo', name: 'Megogo', category: 'other' },
  { id: 'uy', slug: 'meliuz', name: 'Meliuz', category: 'other' },
  { id: 'cq', slug: 'mercado', name: 'Mercado', category: 'other' },
  { id: 'dg', slug: 'mercari', name: 'Mercari', category: 'other' },
  { id: 'vy', slug: 'meta', name: 'Meta', category: 'other' },
  { id: 'bv', slug: 'metro', name: 'Metro', category: 'other' },
  { id: 'he', slug: 'mewt', name: 'Mewt', category: 'other' },
  { id: 'mc', slug: 'michat', name: 'Michat', category: 'other' },
  { id: 'ey', slug: 'miloan', name: 'Miloan', category: 'other' },
  { id: 'op', slug: 'miratorg', name: 'Miratorg', category: 'other' },
  { id: 'yr', slug: 'miravia', name: 'Miravia', category: 'other' },
  { id: 'bg', slug: 'mixmart', name: 'Mixmart', category: 'other' },
  { id: 'gy', slug: 'miyachat', name: 'Miyachat', category: 'other' },
  { id: 'fo', slug: 'mobikwik', name: 'Mobikwik', category: 'other' },
  { id: 'wk', slug: 'mobile01', name: 'Mobile01', category: 'other' },
  { id: 'gm', slug: 'mocospace', name: 'Mocospace', category: 'other' },
  { id: 'hc', slug: 'momo', name: 'Momo', category: 'other' },
  { id: 'py', slug: 'monese', name: 'Monese', category: 'other' },
  { id: 'xp', slug: 'monetaru', name: 'Monetaru', category: 'other' },
  { id: 'qo', slug: 'moneylion', name: 'Moneylion', category: 'other' },
  { id: 'qg', slug: 'moneypay', name: 'Moneypay', category: 'other' },
  { id: 'qt', slug: 'money-ontrol', name: 'Moneyсontrol', category: 'other' },
  { id: 'ji', slug: 'monobank', name: 'Monobank', category: 'other' },
  { id: 'bu', slug: 'monobankindia', name: 'Monobankindia', category: 'other' },
  { id: 'ce', slug: 'mosru', name: 'Mosru', category: 'other' },
  { id: 'xq', slug: 'mpl', name: 'Mpl', category: 'other' },
  { id: 'lw', slug: 'mrgreen', name: 'Mrgreen', category: 'other' },
  { id: 'ej', slug: 'mrq', name: 'Mrq', category: 'other' },
  { id: 'da', slug: 'mts-cashback', name: 'Mts cashback', category: 'other' },
  { id: 'ha', slug: 'my11circle', name: 'My11circle', category: 'other' },
  { id: 'ur', slug: 'mydailycash', name: 'Mydailycash', category: 'other' },
  { id: 'qa', slug: 'myfishka', name: 'Myfishka', category: 'other' },
  { id: 'ae', slug: 'myglo', name: 'Myglo', category: 'other' },
  { id: 'iw', slug: 'mylavash', name: 'Mylavash', category: 'other' },
  { id: 'fy', slug: 'mylove', name: 'Mylove', category: 'other' },
  { id: 'mu', slug: 'mymusictaste', name: 'Mymusictaste', category: 'other' },
  { id: 'nl', slug: 'myntra', name: 'Myntra', category: 'other' },
  { id: 'jm', slug: 'mzadqatar', name: 'Mzadqatar', category: 'other' },
  { id: 'je', slug: 'nanovest', name: 'Nanovest', category: 'other' },
  { id: 'nv', slug: 'naver', name: 'Naver', category: 'other' },
  { id: 'sw', slug: 'ncsoft', name: 'Ncsoft', category: 'other' },
  { id: 'rn', slug: 'neftm', name: 'Neftm', category: 'other' },
  { id: 'ef', slug: 'nextdoor', name: 'Nextdoor', category: 'other' },
  { id: 'px', slug: 'nifty', name: 'Nifty', category: 'other' },
  { id: 'ew', slug: 'nike', name: 'Nike', category: 'other' },
  { id: 'kz', slug: 'nimotv', name: 'Nimotv', category: 'other' },
  { id: 'dv', slug: 'nobroker', name: 'Nobroker', category: 'other' },
  { id: 'tf', slug: 'noon', name: 'Noon', category: 'other' },
  { id: 'xo', slug: 'notifire', name: 'Notifire', category: 'other' },
  { id: 'ms', slug: 'novaposhta', name: 'Novaposhta', category: 'other' },
  { id: 'pg', slug: 'nrj-music-awards', name: 'Nrj music awards', category: 'other' },
  { id: 'zy', slug: 'nttgame', name: 'Nttgame', category: 'other' },
  { id: 'zm', slug: 'offerup', name: 'Offerup', category: 'other' },
  { id: 'uz', slug: 'offgamers', name: 'Offgamers', category: 'other' },
  { id: 'vm', slug: 'okcupid', name: 'Okcupid', category: 'other' },
  { id: 'og', slug: 'okko', name: 'Okko', category: 'other' },
  { id: 'lr', slug: 'okta', name: 'Okta', category: 'other' },
  { id: 'ly', slug: 'olacabs', name: 'Olacabs', category: 'other' },
  { id: 'ns', slug: 'oldubil', name: 'Oldubil', category: 'other' },
  { id: 'aj', slug: 'oneaset', name: 'Oneaset', category: 'other' },
  { id: 'ue', slug: 'onet', name: 'Onet', category: 'other' },
  { id: 'ob', slug: 'onlinerby', name: 'Onlinerby', category: 'other' },
  { id: 'zf', slug: 'ontaxi', name: 'Ontaxi', category: 'other' },
  { id: 'lo', slug: 'oppo', name: 'Oppo', category: 'other' },
  { id: 'qh', slug: 'oriflame', name: 'Oriflame', category: 'other' },
  { id: 'xh', slug: 'ovo', name: 'Ovo', category: 'other' },
  { id: 'sg', slug: 'ozon', name: 'Ozon', category: 'other' },
  { id: 'cw', slug: 'paddypower', name: 'Paddypower', category: 'other' },
  { id: 'gg', slug: 'pagsmile', name: 'Pagsmile', category: 'other' },
  { id: 'dk', slug: 'pairs', name: 'Pairs', category: 'other' },
  { id: 'zr', slug: 'papara', name: 'Papara', category: 'other' },
  { id: 'wo', slug: 'parkplus', name: 'Parkplus', category: 'other' },
  { id: 'dn', slug: 'paxful', name: 'Paxful', category: 'other' },
  { id: 'qb', slug: 'payberry', name: 'Payberry', category: 'other' },
  { id: 'xz', slug: 'paycell', name: 'Paycell', category: 'other' },
  { id: 'nc', slug: 'payoneer', name: 'Payoneer', category: 'other' },
  { id: 'jq', slug: 'paysafecard', name: 'Paysafecard', category: 'other' },
  { id: 'tr', slug: 'paysend', name: 'Paysend', category: 'other' },
  { id: 'yp', slug: 'payzapp', name: 'Payzapp', category: 'other' },
  { id: 'at', slug: 'perfluence', name: 'Perfluence', category: 'other' },
  { id: 'fx', slug: 'pgbonus', name: 'Pgbonus', category: 'other' },
  { id: 'fc', slug: 'pharmeasy', name: 'Pharmeasy', category: 'other' },
  { id: 'fp', slug: 'phound', name: 'Phound', category: 'other' },
  { id: 'ev', slug: 'picpay', name: 'Picpay', category: 'other' },
  { id: 'ro', slug: 'pingcode', name: 'Pingcode', category: 'other' },
  { id: 'jh', slug: 'pingpong', name: 'Pingpong', category: 'other' },
  { id: 'sz', slug: 'pivko24', name: 'Pivko24', category: 'other' },
  { id: 'ch', slug: 'pocket52', name: 'Pocket52', category: 'other' },
  { id: 'pj', slug: 'podeli', name: 'Podeli', category: 'other' },
  { id: 'pf', slug: 'pof-com', name: 'Pof.com', category: 'other' },
  { id: 'rg', slug: 'porbet', name: 'Porbet', category: 'other' },
  { id: 'oz', slug: 'poshmark', name: 'Poshmark', category: 'other' },
  { id: 'lq', slug: 'potato', name: 'Potato', category: 'other' },
  { id: 'fj', slug: 'potato-chat', name: 'Potato chat', category: 'other' },
  { id: 'dx', slug: 'powerkredite', name: 'Powerkredite', category: 'other' },
  { id: 'po', slug: 'premium-one', name: 'Premium.one', category: 'other' },
  { id: 'wu', slug: 'privetmir', name: 'Privetmir', category: 'other' },
  { id: 'aa', slug: 'probo', name: 'Probo', category: 'other' },
  { id: 'cm', slug: 'prom', name: 'Prom', category: 'other' },
  { id: 'dp', slug: 'protonmail', name: 'Protonmail', category: 'other' },
  { id: 'lk', slug: 'pureplatfrom', name: 'Pureplatfrom', category: 'other' },
  { id: 'ny', slug: 'pyro-music', name: 'Pyro music', category: 'other' },
  { id: 'vf', slug: 'q12-trivia', name: 'Q12 trivia', category: 'other' },
  { id: 'eq', slug: 'qoo10', name: 'Qoo10', category: 'other' },
  { id: 'zw', slug: 'quack', name: 'Quack', category: 'other' },
  { id: 'cc', slug: 'quipp', name: 'Quipp', category: 'other' },
  { id: 'tc', slug: 'rambler', name: 'Rambler', category: 'other' },
  { id: 'jp', slug: 'rbt', name: 'Rbt', category: 'other' },
  { id: 'xu', slug: 'recargapay', name: 'Recargapay', category: 'other' },
  { id: 'qf', slug: 'redbook', name: 'Redbook', category: 'other' },
  { id: 'ci', slug: 'redbus', name: 'Redbus', category: 'other' },
  { id: 'co', slug: 'rediffmail', name: 'Rediffmail', category: 'other' },
  { id: 'ow', slug: 'regru', name: 'Regru', category: 'other' },
  { id: 'zj', slug: 'robinhood', name: 'Robinhood', category: 'other' },
  { id: 'ga', slug: 'roposo', name: 'Roposo', category: 'other' },
  { id: 'qm', slug: 'rosakhutor', name: 'Rosakhutor', category: 'other' },
  { id: 'ku', slug: 'royalwin', name: 'Royalwin', category: 'other' },
  { id: 'km', slug: 'rozetka', name: 'Rozetka', category: 'other' },
  { id: 'mn', slug: 'rrsa', name: 'Rrsa', category: 'other' },
  { id: 'ec', slug: 'rummyculture', name: 'Rummyculture', category: 'other' },
  { id: 'fl', slug: 'rummyloot', name: 'Rummyloot', category: 'other' },
  { id: 'xb', slug: 'rummyola', name: 'Rummyola', category: 'other' },
  { id: 'so', slug: 'rummywealth', name: 'Rummywealth', category: 'other' },
  { id: 'kv', slug: 'rush', name: 'Rush', category: 'other' },
  { id: 'ay', slug: 'ruten', name: 'Ruten', category: 'other' },
  { id: 'ui', slug: 'rutube', name: 'Rutube', category: 'other' },
  { id: 'gs', slug: 'samsungshop', name: 'Samsungshop', category: 'other' },
  { id: 'lj', slug: 'santander', name: 'Santander', category: 'other' },
  { id: 'pw', slug: 'sellmonitor', name: 'Sellmonitor', category: 'other' },
  { id: 'vv', slug: 'seosprint', name: 'Seosprint', category: 'other' },
  { id: 'zg', slug: 'setel', name: 'Setel', category: 'other' },
  { id: 'rx', slug: 'sheerid', name: 'Sheerid', category: 'other' },
  { id: 'vg', slug: 'shellbox', name: 'Shellbox', category: 'other' },
  { id: 'fs', slug: 'ikayet-var', name: 'Şikayet var', category: 'other' },
  { id: 'np', slug: 'siply', name: 'Siply', category: 'other' },
  { id: 'eo', slug: 'sizeer', name: 'Sizeer', category: 'other' },
  { id: 'wg', slug: 'skout', name: 'Skout', category: 'other' },
  { id: 'sk', slug: 'skroutz', name: 'Skroutz', category: 'other' },
  { id: 'rc', slug: 'skype', name: 'Skype', category: 'other' },
  { id: 'pb', slug: 'skytv', name: 'Skytv', category: 'other' },
  { id: 'wm', slug: 'smo71', name: 'Smo71', category: 'other' },
  { id: 'ph', slug: 'snappfood', name: 'Snappfood', category: 'other' },
  { id: 'sf', slug: 'sneakersnstuff', name: 'Sneakersnstuff', category: 'other' },
  { id: 'ia', slug: 'socios', name: 'Socios', category: 'other' },
  { id: 'jy', slug: 'sorare', name: 'Sorare', category: 'other' },
  { id: 'mx', slug: 'soulapp', name: 'Soulapp', category: 'other' },
  { id: 'ky', slug: 'spatenoktoberfest', name: 'Spatenoktoberfest', category: 'other' },
  { id: 'va', slug: 'sportgully', name: 'Sportgully', category: 'other' },
  { id: 'cd', slug: 'spothit', name: 'Spothit', category: 'other' },
  { id: 'nt', slug: 'sravni', name: 'Sravni', category: 'other' },
  { id: 'la', slug: 'ssoidnet', name: 'Ssoidnet', category: 'other' },
  { id: 'sr', slug: 'starbucks', name: 'Starbucks', category: 'other' },
  { id: 'jo', slug: 'sticpay', name: 'Sticpay', category: 'other' },
  { id: 'vj', slug: 'stormgain', name: 'Stormgain', category: 'other' },
  { id: 'lc', slug: 'subito', name: 'Subito', category: 'other' },
  { id: 'ca', slug: 'supers', name: 'Supers', category: 'other' },
  { id: 'gd', slug: 'surveytime', name: 'Surveytime', category: 'other' },
  { id: 'jx', slug: 'swiggy', name: 'Swiggy', category: 'other' },
  { id: 'hg', slug: 'switips', name: 'Switips', category: 'other' },
  { id: 'tq', slug: 'swvl', name: 'Swvl', category: 'other' },
  { id: 'xc', slug: 'synottip', name: 'Synottip', category: 'other' },
  { id: 'aw', slug: 'taikang', name: 'Taikang', category: 'other' },
  { id: 'xw', slug: 'taki', name: 'Taki', category: 'other' },
  { id: 'ei', slug: 'taksheel', name: 'Taksheel', category: 'other' },
  { id: 'xr', slug: 'tango', name: 'Tango', category: 'other' },
  { id: 'wh', slug: 'tantan', name: 'Tantan', category: 'other' },
  { id: 'qd', slug: 'taobao', name: 'Taobao', category: 'other' },
  { id: 'uc', slug: 'tatneft', name: 'Tatneft', category: 'other' },
  { id: 'ih', slug: 'teenpattistarpro', name: 'Teenpattistarpro', category: 'other' },
  { id: 'eh', slug: 'telegram-2-0', name: 'Telegram 2.0', category: 'other' },
  { id: 'ep', slug: 'temu', name: 'Temu', category: 'other' },
  { id: 'qq', slug: 'tencent-qq', name: 'Tencent qq', category: 'other' },
  { id: 'cr', slug: 'tenchat', name: 'Tenchat', category: 'other' },
  { id: 'vr', slug: 'test', name: 'Test', category: 'other' },
  { id: 'lz', slug: 'things', name: 'Things', category: 'other' },
  { id: 'nm', slug: 'thisshop', name: 'Thisshop', category: 'other' },
  { id: 'rb', slug: 'tick', name: 'Tick', category: 'other' },
  { id: 'gp', slug: 'ticketmaster', name: 'Ticketmaster', category: 'other' },
  { id: 'lf', slug: 'tiktok-douyin', name: 'Tiktok/douyin', category: 'other' },
  { id: 'xd', slug: 'tokopedia', name: 'Tokopedia', category: 'other' },
  { id: 'uq', slug: 'topdetal', name: 'Topdetal', category: 'other' },
  { id: 'nr', slug: 'tosla', name: 'Tosla', category: 'other' },
  { id: 'fm', slug: 'touchance', name: 'Touchance', category: 'other' },
  { id: 'bs', slug: 'tradeup', name: 'Tradeup', category: 'other' },
  { id: 'gc', slug: 'tradingview', name: 'Tradingview', category: 'other' },
  { id: 'mw', slug: 'transfergo', name: 'Transfergo', category: 'other' },
  { id: 'nq', slug: 'trip', name: 'Trip', category: 'other' },
  { id: 'tl', slug: 'truecaller', name: 'Truecaller', category: 'other' },
  { id: 'jt', slug: 'turkiyepetrolleri', name: 'Turkiyepetrolleri', category: 'other' },
  { id: 'ee', slug: 'twilio', name: 'Twilio', category: 'other' },
  { id: 'cp', slug: 'uklon', name: 'Uklon', category: 'other' },
  { id: 'hu', slug: 'ukrnet', name: 'Ukrnet', category: 'other' },
  { id: 'hh', slug: 'uplay', name: 'Uplay', category: 'other' },
  { id: 'of', slug: 'urent-jet-rusharing', name: 'Urent/jet/rusharing', category: 'other' },
  { id: 'bh', slug: 'uteka', name: 'Uteka', category: 'other' },
  { id: 'ao', slug: 'uu163', name: 'Uu163', category: 'other' },
  { id: 'cl', slug: 'uwin', name: 'Uwin', category: 'other' },
  { id: 'yy', slug: 'venmo', name: 'Venmo', category: 'other' },
  { id: 'kn', slug: 'verse', name: 'Verse', category: 'other' },
  { id: 'fv', slug: 'vidio', name: 'Vidio', category: 'other' },
  { id: 'kc', slug: 'vinted', name: 'Vinted', category: 'other' },
  { id: 'no', slug: 'virgo', name: 'Virgo', category: 'other' },
  { id: 'kx', slug: 'vivo', name: 'Vivo', category: 'other' },
  { id: 'oq', slug: 'vlife', name: 'Vlife', category: 'other' },
  { id: 'sc', slug: 'voggt', name: 'Voggt', category: 'other' },
  { id: 'eb', slug: 'voltz', name: 'Voltz', category: 'other' },
  { id: 'wr', slug: 'walmart', name: 'Walmart', category: 'other' },
  { id: 'cv', slug: 'washxpress', name: 'Washxpress', category: 'other' },
  { id: 'wb', slug: 'wechat', name: 'Wechat', category: 'other' },
  { id: 'kf', slug: 'weibo', name: 'Weibo', category: 'other' },
  { id: 'mf', slug: 'weidian', name: 'Weidian', category: 'other' },
  { id: 'th', slug: 'weststein', name: 'Weststein', category: 'other' },
  { id: 'ja', slug: 'weverse', name: 'Weverse', category: 'other' },
  { id: 'qj', slug: 'whoosh', name: 'Whoosh', category: 'other' },
  { id: 'jb', slug: 'wing-money', name: 'Wing money', category: 'other' },
  { id: 'ta', slug: 'wink', name: 'Wink', category: 'other' },
  { id: 'mp', slug: 'winmasters', name: 'Winmasters', category: 'other' },
  { id: 'vs', slug: 'winzogame', name: 'Winzogame', category: 'other' },
  { id: 'xv', slug: 'wish', name: 'Wish', category: 'other' },
  { id: 'xl', slug: 'wmaraci', name: 'Wmaraci', category: 'other' },
  { id: 'ar', slug: 'wondermart', name: 'Wondermart', category: 'other' },
  { id: 'qx', slug: 'worldremit', name: 'Worldremit', category: 'other' },
  { id: 'bd', slug: 'x5id', name: 'X5id', category: 'other' },
  { id: 'fa', slug: 'xadrezfeliz', name: 'Xadrezfeliz', category: 'other' },
  { id: 'yu', slug: 'xiaomi', name: 'Xiaomi', category: 'other' },
  { id: 'nw', slug: 'ximalaya', name: 'Ximalaya', category: 'other' },
  { id: 'vn', slug: 'yaay', name: 'Yaay', category: 'other' },
  { id: 'mb', slug: 'yahoo', name: 'Yahoo', category: 'other' },
  { id: 'yl', slug: 'yalla', name: 'Yalla', category: 'other' },
  { id: 'wy', slug: 'yami', name: 'Yami', category: 'other' },
  { id: 'wf', slug: 'yandexgo', name: 'Yandexgo', category: 'other' },
  { id: 'kj', slug: 'yappy', name: 'Yappy', category: 'other' },
  { id: 'yi', slug: 'yemeksepeti', name: 'Yemeksepeti', category: 'other' },
  { id: 'dc', slug: 'yikyak', name: 'Yikyak', category: 'other' },
  { id: 'wl', slug: 'yougotagift', name: 'Yougotagift', category: 'other' },
  { id: 'gb', slug: 'youstar', name: 'Youstar', category: 'other' },
  { id: 'sm', slug: 'yowin', name: 'Yowin', category: 'other' },
  { id: 'uh', slug: 'yubo', name: 'Yubo', category: 'other' },
  { id: 'ye', slug: 'zaleycash', name: 'Zaleycash', category: 'other' },
  { id: 'mj', slug: 'zalo', name: 'Zalo', category: 'other' },
  { id: 'ys', slug: 'zcity', name: 'Zcity', category: 'other' },
  { id: 'ps', slug: 'zdorov', name: 'Zdorov', category: 'other' },
  { id: 'em', slug: 'z-delivery', name: 'Zédelivery', category: 'other' },
  { id: 'qy', slug: 'zhihu', name: 'Zhihu', category: 'other' },
  { id: 'zd', slug: 'zilch', name: 'Zilch', category: 'other' },
  { id: 'zh', slug: 'zoho', name: 'Zoho', category: 'other' },
  { id: 'mz', slug: 'zolushka', name: 'Zolushka', category: 'other' },
  { id: 'dy', slug: 'zomato', name: 'Zomato', category: 'other' },
  { id: 'mi', slug: 'zupee', name: 'Zupee', category: 'other' },
  { id: 'mh', slug: 'mh', name: 'Ашан', category: 'other' },
  { id: 'st', slug: 'st', name: 'Ашан', category: 'other' },
  { id: 'ft', slug: 'ft', name: 'Букмекерские', category: 'other' },
  { id: 'nb', slug: 'nb', name: 'Верный', category: 'other' },
  { id: 'bj', slug: 'bj', name: 'Вита экспресс', category: 'other' },
  { id: 'vk', slug: 'vk', name: 'Вконтакте', category: 'other' },
  { id: 'sh', slug: 'sh', name: 'Вкусвилл', category: 'other' },
  { id: 'br', slug: 'br', name: 'Вкусно и точка', category: 'other' },
  { id: 'js', slug: 'js', name: 'Голос', category: 'other' },
  { id: 'rj', slug: 'rj', name: 'Детский мир', category: 'other' },
  { id: 'ux', slug: 'ux', name: 'Домовой', category: 'other' },
  { id: 'we', slug: 'we', name: 'Другвокруг', category: 'other' },
  { id: 'io', slug: 'io', name: 'Здравсити', category: 'other' },
  { id: 'yb', slug: 'yb', name: 'Квартплата+', category: 'other' },
  { id: 'fq', slug: 'fq', name: 'Контур', category: 'other' },
  { id: 'ct', slug: 'ct', name: 'Кухнянарайоне', category: 'other' },
  { id: 'tz', slug: 'tz', name: 'Лейка', category: 'other' },
  { id: 'xm', slug: 'xm', name: 'Лэтуаль', category: 'other' },
  { id: 'ot', slug: 'ot', name: 'Любой другой', category: 'other' },
  { id: 'mg', slug: 'mg', name: 'Магнит', category: 'other' },
  { id: 'qp', slug: 'qp', name: 'Максавит', category: 'other' },
  { id: 'tk', slug: 'tk', name: 'Мвидео', category: 'other' },
  { id: 'qs', slug: 'qs', name: 'Мирзнакомств', category: 'other' },
  { id: 'ok', slug: 'ok', name: 'Одноклассники', category: 'other' },
  { id: 'ty', slug: 'ty', name: 'Окей', category: 'other' },
  { id: 'yz', slug: 'yz', name: 'Около', category: 'other' },
  { id: 'vl', slug: 'vl', name: 'Ортека', category: 'other' },
  { id: 'pl', slug: 'pl', name: 'Перекресток', category: 'other' },
  { id: 'full', slug: 'full', name: 'Полная аренда', category: 'other' },
  { id: 'qc', slug: '2020', name: 'Праймериз 2020', category: 'other' },
  { id: 'cy', slug: 'cy', name: 'Рса', category: 'other' },
  { id: 'uj', slug: 'hampion-asino', name: 'Сhampionсasino', category: 'other' },
  { id: 'jr', slug: 'jr', name: 'Самокат', category: 'other' },
  { id: 'sl', slug: 'sl', name: 'Сбераптека', category: 'other' },
  { id: 'xj', slug: 'xj', name: 'Сбермаркет', category: 'other' },
  { id: 'be', slug: 'be', name: 'Сбермегамаркет', category: 'other' },
  { id: 'yk', slug: 'yk', name: 'Спортмастер', category: 'other' },
  { id: 'hj', slug: 'hj', name: 'Столото', category: 'other' },
  { id: 'xa', slug: 'xa', name: 'Улыбкарадуги', category: 'other' },
  { id: 'yq', slug: 'yq', name: 'Фокстрот', category: 'other' },
  { id: 'vh', slug: 'vh', name: 'Штолле', category: 'other' },
  { id: 'ke', slug: 'ke', name: 'Эльдорадо', category: 'other' },
  { id: 'ut', slug: 'ut', name: 'Энергобум', category: 'other' },
  { id: 'ym', slug: 'ym', name: 'Юла', category: 'other' },
  { id: 'ya', slug: 'ya', name: 'Яндекс', category: 'other' },
  { id: 'bi', slug: 'ys4fun', name: '勇仕网络ys4fun', category: 'other' },
  { id: 'cu', slug: 'cu', name: '炙热星河', category: 'other' },
  { id: 'yd', slug: 'mihuashi', name: '米画师mihuashi', category: 'other' },
]



export const COUNTRIES: CountryPrice[] = [
  { iso: 'FR', code: 'fr', name: 'France', priceUsd: 0.35, priceXaf: usdToXaf(0.35), phonePrefix: '+33', flag: '🇫🇷' },
  { iso: 'DE', code: 'de', name: 'Germany', priceUsd: 0.4, priceXaf: usdToXaf(0.4), phonePrefix: '+49', flag: '🇩🇪' },
  { iso: 'GB', code: 'gb', name: 'United Kingdom', priceUsd: 0.5, priceXaf: usdToXaf(0.5), phonePrefix: '+44', flag: '🇬🇧' },
  { iso: 'US', code: 'us', name: 'United States', priceUsd: 0.55, priceXaf: usdToXaf(0.55), phonePrefix: '+1', flag: '🇺🇸' },
  { iso: 'CA', code: 'ca', name: 'Canada', priceUsd: 0.45, priceXaf: usdToXaf(0.45), phonePrefix: '+1', flag: '🇨🇦' },
  { iso: 'ES', code: 'es', name: 'Spain', priceUsd: 0.3, priceXaf: usdToXaf(0.3), phonePrefix: '+34', flag: '🇪🇸' },
  { iso: 'IT', code: 'it', name: 'Italy', priceUsd: 0.35, priceXaf: usdToXaf(0.35), phonePrefix: '+39', flag: '🇮🇹' },
  { iso: 'PT', code: 'pt', name: 'Portugal', priceUsd: 0.3, priceXaf: usdToXaf(0.3), phonePrefix: '+351', flag: '🇵🇹' },
  { iso: 'NL', code: 'nl', name: 'Netherlands', priceUsd: 0.4, priceXaf: usdToXaf(0.4), phonePrefix: '+31', flag: '🇳🇱' },
  { iso: 'BE', code: 'be', name: 'Belgium', priceUsd: 0.35, priceXaf: usdToXaf(0.35), phonePrefix: '+32', flag: '🇧🇪' },
  { iso: 'SE', code: 'se', name: 'Sweden', priceUsd: 0.5, priceXaf: usdToXaf(0.5), phonePrefix: '+46', flag: '🇸🇪' },
  { iso: 'NO', code: 'no', name: 'Norway', priceUsd: 0.6, priceXaf: usdToXaf(0.6), phonePrefix: '+47', flag: '🇳🇴' },
  { iso: 'DK', code: 'dk', name: 'Denmark', priceUsd: 0.55, priceXaf: usdToXaf(0.55), phonePrefix: '+45', flag: '🇩🇰' },
  { iso: 'FI', code: 'fi', name: 'Finland', priceUsd: 0.5, priceXaf: usdToXaf(0.5), phonePrefix: '+358', flag: '🇫🇮' },
  { iso: 'IE', code: 'ie', name: 'Ireland', priceUsd: 0.45, priceXaf: usdToXaf(0.45), phonePrefix: '+353', flag: '🇮🇪' },
  { iso: 'RO', code: 'ro', name: 'Romania', priceUsd: 0.25, priceXaf: usdToXaf(0.25), phonePrefix: '+40', flag: '🇷🇴' },
  { iso: 'PL', code: 'pl', name: 'Poland', priceUsd: 0.25, priceXaf: usdToXaf(0.25), phonePrefix: '+48', flag: '🇵🇱' },
  { iso: 'GR', code: 'gr', name: 'Greece', priceUsd: 0.3, priceXaf: usdToXaf(0.3), phonePrefix: '+30', flag: '🇬🇷' },
  { iso: 'HU', code: 'hu', name: 'Hungary', priceUsd: 0.25, priceXaf: usdToXaf(0.25), phonePrefix: '+36', flag: '🇭🇺' },
  { iso: 'AT', code: 'at', name: 'Austria', priceUsd: 0.4, priceXaf: usdToXaf(0.4), phonePrefix: '+43', flag: '🇦🇹' },
  { iso: 'CH', code: 'ch', name: 'Switzerland', priceUsd: 0.7, priceXaf: usdToXaf(0.7), phonePrefix: '+41', flag: '🇨🇭' },
  { iso: 'AU', code: 'au', name: 'Australia', priceUsd: 0.55, priceXaf: usdToXaf(0.55), phonePrefix: '+61', flag: '🇦🇺' },
  { iso: 'NZ', code: 'nz', name: 'New Zealand', priceUsd: 0.5, priceXaf: usdToXaf(0.5), phonePrefix: '+64', flag: '🇳🇿' },
  { iso: 'JP', code: 'jp', name: 'Japan', priceUsd: 0.65, priceXaf: usdToXaf(0.65), phonePrefix: '+81', flag: '🇯🇵' },
  { iso: 'KR', code: 'kr', name: 'South Korea', priceUsd: 0.6, priceXaf: usdToXaf(0.6), phonePrefix: '+82', flag: '🇰🇷' },
  { iso: 'CN', code: 'cn', name: 'China', priceUsd: 0.45, priceXaf: usdToXaf(0.45), phonePrefix: '+86', flag: '🇨🇳' },
  { iso: 'IN', code: 'in', name: 'India', priceUsd: 0.2, priceXaf: usdToXaf(0.2), phonePrefix: '+91', flag: '🇮🇳' },
  { iso: 'ID', code: 'id', name: 'Indonesia', priceUsd: 0.25, priceXaf: usdToXaf(0.25), phonePrefix: '+62', flag: '🇮🇩' },
  { iso: 'MY', code: 'my', name: 'Malaysia', priceUsd: 0.3, priceXaf: usdToXaf(0.3), phonePrefix: '+60', flag: '🇲🇾' },
  { iso: 'PH', code: 'ph', name: 'Philippines', priceUsd: 0.25, priceXaf: usdToXaf(0.25), phonePrefix: '+63', flag: '🇵🇭' },
  { iso: 'SG', code: 'sg', name: 'Singapore', priceUsd: 0.55, priceXaf: usdToXaf(0.55), phonePrefix: '+65', flag: '🇸🇬' },
  { iso: 'TH', code: 'th', name: 'Thailand', priceUsd: 0.3, priceXaf: usdToXaf(0.3), phonePrefix: '+66', flag: '🇹🇭' },
  { iso: 'VN', code: 'vn', name: 'Vietnam', priceUsd: 0.25, priceXaf: usdToXaf(0.25), phonePrefix: '+84', flag: '🇻🇳' },
  { iso: 'ZA', code: 'za', name: 'South Africa', priceUsd: 0.3, priceXaf: usdToXaf(0.3), phonePrefix: '+27', flag: '🇿🇦' },
  { iso: 'NG', code: 'ng', name: 'Nigeria', priceUsd: 0.35, priceXaf: usdToXaf(0.35), phonePrefix: '+234', flag: '🇳🇬' },
  { iso: 'KE', code: 'ke', name: 'Kenya', priceUsd: 0.3, priceXaf: usdToXaf(0.3), phonePrefix: '+254', flag: '🇰🇪' },
  { iso: 'EG', code: 'eg', name: 'Egypt', priceUsd: 0.25, priceXaf: usdToXaf(0.25), phonePrefix: '+20', flag: '🇪🇬' },
  { iso: 'MA', code: 'ma', name: 'Morocco', priceUsd: 0.3, priceXaf: usdToXaf(0.3), phonePrefix: '+212', flag: '🇲🇦' },
  { iso: 'CM', code: 'cm', name: 'Cameroon', priceUsd: 0.35, priceXaf: usdToXaf(0.35), phonePrefix: '+237', flag: '🇨🇲' },
  { iso: 'CI', code: 'ci', name: "Côte d'Ivoire", priceUsd: 0.3, priceXaf: usdToXaf(0.3), phonePrefix: '+225', flag: '🇨🇮' },
  { iso: 'SN', code: 'sn', name: 'Senegal', priceUsd: 0.3, priceXaf: usdToXaf(0.3), phonePrefix: '+221', flag: '🇸🇳' },
  { iso: 'ML', code: 'ml', name: 'Mali', priceUsd: 0.25, priceXaf: usdToXaf(0.25), phonePrefix: '+223', flag: '🇲🇱' },
  { iso: 'BF', code: 'bf', name: 'Burkina Faso', priceUsd: 0.25, priceXaf: usdToXaf(0.25), phonePrefix: '+226', flag: '🇧🇫' },
  { iso: 'TG', code: 'tg', name: 'Togo', priceUsd: 0.25, priceXaf: usdToXaf(0.25), phonePrefix: '+228', flag: '🇹🇬' },
  { iso: 'BJ', code: 'bj', name: 'Benin', priceUsd: 0.25, priceXaf: usdToXaf(0.25), phonePrefix: '+229', flag: '🇧🇯' },
  { iso: 'NE', code: 'ne', name: 'Niger', priceUsd: 0.25, priceXaf: usdToXaf(0.25), phonePrefix: '+227', flag: '🇳🇪' },
  { iso: 'TD', code: 'td', name: 'Chad', priceUsd: 0.25, priceXaf: usdToXaf(0.25), phonePrefix: '+235', flag: '🇹🇩' },
  { iso: 'CF', code: 'cf', name: 'Central African Republic', priceUsd: 0.25, priceXaf: usdToXaf(0.25), phonePrefix: '+236', flag: '🇨🇫' },
  { iso: 'GA', code: 'ga', name: 'Gabon', priceUsd: 0.35, priceXaf: usdToXaf(0.35), phonePrefix: '+241', flag: '🇬🇦' },
  { iso: 'CG', code: 'cg', name: 'Congo', priceUsd: 0.3, priceXaf: usdToXaf(0.3), phonePrefix: '+242', flag: '🇨🇬' },
  { iso: 'CD', code: 'cd', name: 'DR Congo', priceUsd: 0.25, priceXaf: usdToXaf(0.25), phonePrefix: '+243', flag: '🇨🇩' },
  { iso: 'AO', code: 'ao', name: 'Angola', priceUsd: 0.35, priceXaf: usdToXaf(0.35), phonePrefix: '+244', flag: '🇦🇴' },
  { iso: 'MZ', code: 'mz', name: 'Mozambique', priceUsd: 0.3, priceXaf: usdToXaf(0.3), phonePrefix: '+258', flag: '🇲🇿' },
  { iso: 'MG', code: 'mg', name: 'Madagascar', priceUsd: 0.25, priceXaf: usdToXaf(0.25), phonePrefix: '+261', flag: '🇲🇬' },
  { iso: 'TZ', code: 'tz', name: 'Tanzania', priceUsd: 0.3, priceXaf: usdToXaf(0.3), phonePrefix: '+255', flag: '🇹🇿' },
  { iso: 'UG', code: 'ug', name: 'Uganda', priceUsd: 0.3, priceXaf: usdToXaf(0.3), phonePrefix: '+256', flag: '🇺🇬' },
  { iso: 'RW', code: 'rw', name: 'Rwanda', priceUsd: 0.3, priceXaf: usdToXaf(0.3), phonePrefix: '+250', flag: '🇷🇼' },
  { iso: 'ET', code: 'et', name: 'Ethiopia', priceUsd: 0.25, priceXaf: usdToXaf(0.25), phonePrefix: '+251', flag: '🇪🇹' },
  { iso: 'GH', code: 'gh', name: 'Ghana', priceUsd: 0.3, priceXaf: usdToXaf(0.3), phonePrefix: '+233', flag: '🇬🇭' },
  { iso: 'ZM', code: 'zm', name: 'Zambia', priceUsd: 0.3, priceXaf: usdToXaf(0.3), phonePrefix: '+260', flag: '🇿🇲' },
  { iso: 'ZW', code: 'zw', name: 'Zimbabwe', priceUsd: 0.3, priceXaf: usdToXaf(0.3), phonePrefix: '+263', flag: '🇿🇼' },
  { iso: 'MW', code: 'mw', name: 'Malawi', priceUsd: 0.25, priceXaf: usdToXaf(0.25), phonePrefix: '+265', flag: '🇲🇼' },
  { iso: 'BW', code: 'bw', name: 'Botswana', priceUsd: 0.35, priceXaf: usdToXaf(0.35), phonePrefix: '+267', flag: '🇧🇼' },
  { iso: 'NA', code: 'na', name: 'Namibia', priceUsd: 0.35, priceXaf: usdToXaf(0.35), phonePrefix: '+264', flag: '🇳🇦' },
  { iso: 'LS', code: 'ls', name: 'Lesotho', priceUsd: 0.3, priceXaf: usdToXaf(0.3), phonePrefix: '+266', flag: '🇱🇸' },
  { iso: 'SZ', code: 'sz', name: 'Eswatini', priceUsd: 0.3, priceXaf: usdToXaf(0.3), phonePrefix: '+268', flag: '🇸🇿' },
  { iso: 'MU', code: 'mu', name: 'Mauritius', priceUsd: 0.4, priceXaf: usdToXaf(0.4), phonePrefix: '+230', flag: '🇲🇺' },
  { iso: 'SC', code: 'sc', name: 'Seychelles', priceUsd: 0.45, priceXaf: usdToXaf(0.45), phonePrefix: '+248', flag: '🇸🇨' },
  { iso: 'KM', code: 'km', name: 'Comoros', priceUsd: 0.3, priceXaf: usdToXaf(0.3), phonePrefix: '+269', flag: '🇰🇲' },
  { iso: 'DJ', code: 'dj', name: 'Djibouti', priceUsd: 0.3, priceXaf: usdToXaf(0.3), phonePrefix: '+253', flag: '🇩🇯' },
  { iso: 'MR', code: 'mr', name: 'Mauritania', priceUsd: 0.25, priceXaf: usdToXaf(0.25), phonePrefix: '+222', flag: '🇲🇷' },
  { iso: 'GM', code: 'gm', name: 'Gambia', priceUsd: 0.3, priceXaf: usdToXaf(0.3), phonePrefix: '+220', flag: '🇬🇲' },
  { iso: 'SL', code: 'sl', name: 'Sierra Leone', priceUsd: 0.25, priceXaf: usdToXaf(0.25), phonePrefix: '+232', flag: '🇸🇱' },
  { iso: 'LR', code: 'lr', name: 'Liberia', priceUsd: 0.25, priceXaf: usdToXaf(0.25), phonePrefix: '+231', flag: '🇱🇷' },
  { iso: 'GN', code: 'gn', name: 'Guinea', priceUsd: 0.25, priceXaf: usdToXaf(0.25), phonePrefix: '+224', flag: '🇬🇳' },
  { iso: 'SO', code: 'so', name: 'Somalia', priceUsd: 0.3, priceXaf: usdToXaf(0.3), phonePrefix: '+252', flag: '🇸🇴' },
  { iso: 'SS', code: 'ss', name: 'South Sudan', priceUsd: 0.3, priceXaf: usdToXaf(0.3), phonePrefix: '+211', flag: '🇸🇸' },
  { iso: 'SD', code: 'sd', name: 'Sudan', priceUsd: 0.25, priceXaf: usdToXaf(0.25), phonePrefix: '+249', flag: '🇸🇩' },
  { iso: 'ER', code: 'er', name: 'Eritrea', priceUsd: 0.25, priceXaf: usdToXaf(0.25), phonePrefix: '+291', flag: '🇪🇷' },
  { iso: 'BI', code: 'bi', name: 'Burundi', priceUsd: 0.25, priceXaf: usdToXaf(0.25), phonePrefix: '+257', flag: '🇧🇮' },
  { iso: 'CV', code: 'cv', name: 'Cape Verde', priceUsd: 0.35, priceXaf: usdToXaf(0.35), phonePrefix: '+238', flag: '🇨🇻' },
  { iso: 'ST', code: 'st', name: 'São Tomé and Príncipe', priceUsd: 0.3, priceXaf: usdToXaf(0.3), phonePrefix: '+239', flag: '🇸🇹' },
  { iso: 'GQ', code: 'gq', name: 'Equatorial Guinea', priceUsd: 0.35, priceXaf: usdToXaf(0.35), phonePrefix: '+240', flag: '🇬🇶' },
]

export function getCountryByIso(iso: string): CountryPrice | undefined {
  return COUNTRIES.find((c) => c.iso === iso)
}

export function getServiceBySlug(slug: string): Service | undefined {
  return SERVICES.find((s) => s.slug === slug)
}
