export {
  adminKeys,
  useAdminAnalytics,
  useAdminUsers,
  useAdminPurchases,
  useAdminActivations,
  useAdminComptes,
  useAdminPieces,
  useAdminPromoCodes,
  useAdminMargins,
  useAdminPackages,
  useDeleteUser,
  useCreatePromoCode,
  useUpdatePromoCode,
  useDeletePromoCode,
  useCreateMargin,
  useUpdateMargin,
  useDeleteMargin,
  useCreatePackage,
  useUpdatePackage,
  useDeletePackage,
  useAdminWallets,
  useAdminPaymentIntents,
} from './use-admin-queries'
