/**
 * SMS Online Pro / Tiger SMS Country Mapping
 *
 * Country IDs are SMS-Activate-style (shared across SMS Online Pro, Tiger SMS, Grizzly).
 * Verified live against the real getCountries response (191 countries).
 *
 * ⚠️  IMPORTANT: Cameroon = ID 41 (NOT 187 as previously assumed).
 */

export interface ProviderCountry {
  /** Numeric ID used by the provider API (passed as `country` param) */
  id: number
  /** English name as returned by getCountries */
  name: string
  /** ISO 3166-1 alpha-2 code if known, else null */
  iso: string | null
}

export const PROVIDER_COUNTRIES: readonly ProviderCountry[] = [
  { id: 0, name: 'russian federation', iso: 'RU' },
  { id: 1, name: 'ukraine', iso: 'UA' },
  { id: 2, name: 'kazakhstan', iso: 'KZ' },
  { id: 3, name: 'china', iso: 'CN' },
  { id: 4, name: 'philippines', iso: 'PH' },
  { id: 5, name: 'myanmar', iso: null },
  { id: 6, name: 'indonesia', iso: 'ID' },
  { id: 7, name: 'malaysia', iso: 'MY' },
  { id: 8, name: 'kenya', iso: 'KE' },
  { id: 9, name: 'tanzania', iso: 'TZ' },
  { id: 10, name: 'viet nam', iso: 'VN' },
  { id: 11, name: 'kyrgyzstan', iso: 'KG' },
  { id: 12, name: 'usa (virtual)', iso: 'US' },
  { id: 13, name: 'israel', iso: 'IL' },
  { id: 14, name: 'hong kong', iso: 'HK' },
  { id: 15, name: 'poland', iso: 'PL' },
  { id: 16, name: 'united kingdom of great britain and northern ireland', iso: 'GB' },
  { id: 17, name: 'madagascar', iso: null },
  { id: 18, name: 'democratic republic of the congo', iso: null },
  { id: 19, name: 'nigeria', iso: 'NG' },
  { id: 20, name: 'macao', iso: null },
  { id: 21, name: 'egypt', iso: 'EG' },
  { id: 22, name: 'india', iso: 'IN' },
  { id: 23, name: 'ireland', iso: 'IE' },
  { id: 24, name: 'cambodia', iso: null },
  { id: 25, name: 'lao people\\u0027s democratic republic', iso: null },
  { id: 26, name: 'haiti', iso: null },
  { id: 27, name: 'c\\u00f4te d\\u0027ivoire', iso: 'CI' },
  { id: 28, name: 'gambia', iso: null },
  { id: 29, name: 'serbia', iso: 'RS' },
  { id: 30, name: 'yemen', iso: 'YE' },
  { id: 31, name: 'south africa', iso: 'ZA' },
  { id: 32, name: 'romania', iso: 'RO' },
  { id: 33, name: 'colombia', iso: 'CO' },
  { id: 34, name: 'estonia', iso: null },
  { id: 35, name: 'azerbaijan', iso: null },
  { id: 36, name: 'canada', iso: 'CA' },
  { id: 37, name: 'morocco', iso: 'MA' },
  { id: 38, name: 'ghana', iso: 'GH' },
  { id: 39, name: 'argentina', iso: 'AR' },
  { id: 40, name: 'uzbekistan', iso: 'UZ' },
  { id: 41, name: 'cameroon', iso: 'CM' },
  { id: 42, name: 'chad', iso: null },
  { id: 43, name: 'germany', iso: 'DE' },
  { id: 44, name: 'lithuania', iso: 'LT' },
  { id: 45, name: 'croatia', iso: 'HR' },
  { id: 46, name: 'sweden', iso: 'SE' },
  { id: 47, name: 'iraq', iso: 'IQ' },
  { id: 48, name: 'netherlands', iso: 'NL' },
  { id: 49, name: 'latvia', iso: 'LV' },
  { id: 50, name: 'austria', iso: 'AT' },
  { id: 51, name: 'belarus', iso: 'BY' },
  { id: 52, name: 'thailand', iso: 'TH' },
  { id: 53, name: 'saudi arabia', iso: 'SA' },
  { id: 54, name: 'mexico', iso: 'MX' },
  { id: 55, name: 'taiwan', iso: 'TW' },
  { id: 56, name: 'spain', iso: 'ES' },
  { id: 57, name: 'iran', iso: 'IR' },
  { id: 58, name: 'algeria', iso: 'DZ' },
  { id: 59, name: 'slovenia', iso: 'SI' },
  { id: 60, name: 'bangladesh', iso: 'BD' },
  { id: 61, name: 'senegal', iso: 'SN' },
  { id: 62, name: 'turkey', iso: 'TR' },
  { id: 63, name: 'czechia', iso: 'CZ' },
  { id: 64, name: 'sri lanka', iso: 'LK' },
  { id: 65, name: 'peru', iso: 'PE' },
  { id: 66, name: 'pakistan', iso: 'PK' },
  { id: 67, name: 'new zealand', iso: 'NZ' },
  { id: 68, name: 'guinea', iso: null },
  { id: 69, name: 'mali', iso: null },
  { id: 70, name: 'venezuela', iso: null },
  { id: 71, name: 'ethiopia', iso: null },
  { id: 72, name: 'mongolia', iso: null },
  { id: 73, name: 'brazil', iso: 'BR' },
  { id: 74, name: 'afghanistan', iso: null },
  { id: 75, name: 'uganda', iso: null },
  { id: 76, name: 'angola', iso: null },
  { id: 77, name: 'cyprus', iso: 'CY' },
  { id: 78, name: 'france', iso: 'FR' },
  { id: 79, name: 'papua new guinea', iso: null },
  { id: 80, name: 'mozambique', iso: null },
  { id: 81, name: 'nepal', iso: null },
  { id: 82, name: 'belgium', iso: 'BE' },
  { id: 83, name: 'bulgaria', iso: 'BG' },
  { id: 84, name: 'hungary', iso: 'HU' },
  { id: 85, name: 'moldova', iso: 'MD' },
  { id: 86, name: 'italy', iso: 'IT' },
  { id: 87, name: 'paraguay', iso: null },
  { id: 88, name: 'honduras', iso: null },
  { id: 89, name: 'tunisia', iso: null },
  { id: 90, name: 'nicaragua', iso: null },
  { id: 91, name: 'timor-leste', iso: null },
  { id: 92, name: 'bolivia', iso: null },
  { id: 93, name: 'costa rica', iso: null },
  { id: 94, name: 'guatemala', iso: null },
  { id: 95, name: 'united arab emirates', iso: null },
  { id: 96, name: 'zimbabwe', iso: null },
  { id: 97, name: 'puerto rico', iso: null },
  { id: 98, name: 'sudan', iso: null },
  { id: 99, name: 'togo', iso: null },
  { id: 100, name: 'kuwait', iso: 'KW' },
  { id: 101, name: 'el salvador', iso: 'SV' },
  { id: 102, name: 'libya', iso: null },
  { id: 103, name: 'jamaica', iso: null },
  { id: 104, name: 'trinidad and tobago', iso: null },
  { id: 105, name: 'ecuador', iso: null },
  { id: 107, name: 'oman', iso: null },
  { id: 108, name: 'bosnia and herzegovina', iso: null },
  { id: 109, name: 'dominican republic', iso: null },
  { id: 110, name: 'syrian arab republic', iso: null },
  { id: 111, name: 'qatar', iso: null },
  { id: 112, name: 'panama', iso: null },
  { id: 113, name: 'cuba', iso: null },
  { id: 114, name: 'mauritania', iso: null },
  { id: 115, name: 'sierra leone', iso: null },
  { id: 116, name: 'jordan', iso: null },
  { id: 117, name: 'portugal', iso: 'PT' },
  { id: 118, name: 'barbados', iso: null },
  { id: 119, name: 'burundi', iso: null },
  { id: 120, name: 'benin', iso: null },
  { id: 121, name: 'brunei', iso: null },
  { id: 122, name: 'bahamas', iso: null },
  { id: 123, name: 'botswana', iso: null },
  { id: 124, name: 'belize', iso: null },
  { id: 125, name: 'central african republic', iso: null },
  { id: 126, name: 'dominica', iso: null },
  { id: 127, name: 'grenada', iso: null },
  { id: 128, name: 'georgia', iso: 'GE' },
  { id: 129, name: 'greece', iso: 'GR' },
  { id: 130, name: 'guinea-bissau', iso: null },
  { id: 131, name: 'guyana', iso: null },
  { id: 132, name: 'iceland', iso: 'IS' },
  { id: 133, name: 'comoros', iso: null },
  { id: 134, name: 'saint kitts and nevis', iso: null },
  { id: 135, name: 'liberia', iso: null },
  { id: 136, name: 'lesotho', iso: null },
  { id: 137, name: 'malawi', iso: null },
  { id: 138, name: 'namibia', iso: null },
  { id: 139, name: 'niger', iso: null },
  { id: 140, name: 'rwanda', iso: null },
  { id: 141, name: 'slovakia', iso: 'SK' },
  { id: 142, name: 'suriname', iso: null },
  { id: 143, name: 'tadjikistan', iso: null },
  { id: 144, name: 'monaco', iso: null },
  { id: 145, name: 'bahrain', iso: 'CH' },
  { id: 146, name: 'r\\u00e9union', iso: null },
  { id: 147, name: 'zambia', iso: null },
  { id: 148, name: 'armenia', iso: null },
  { id: 149, name: 'somalia', iso: 'FI' },
  { id: 150, name: 'congo', iso: 'AU' },
  { id: 151, name: 'chile', iso: 'JP' },
  { id: 152, name: 'burkina faso', iso: 'NO' },
  { id: 153, name: 'lebanon', iso: null },
  { id: 154, name: 'gabon', iso: 'KR' },
  { id: 155, name: 'albania', iso: null },
  { id: 156, name: 'uruguay', iso: null },
  { id: 157, name: 'mauritius', iso: null },
  { id: 158, name: 'bhutan', iso: null },
  { id: 159, name: 'maldives', iso: null },
  { id: 160, name: 'guadeloupe', iso: null },
  { id: 161, name: 'turkmenistan', iso: null },
  { id: 162, name: 'french guiana', iso: null },
  { id: 163, name: 'finland', iso: null },
  { id: 164, name: 'saint lucia', iso: null },
  { id: 165, name: 'luxembourg', iso: null },
  { id: 166, name: 'saint vincent and the grenadines', iso: null },
  { id: 167, name: 'equatorial guinea', iso: null },
  { id: 168, name: 'djibouti', iso: null },
  { id: 169, name: 'antigua and barbuda', iso: 'LB' },
  { id: 170, name: 'cayman islands', iso: null },
  { id: 171, name: 'montenegro', iso: 'LU' },
  { id: 172, name: 'denmark', iso: null },
  { id: 173, name: 'switzerland', iso: null },
  { id: 174, name: 'norway', iso: null },
  { id: 175, name: 'australia', iso: null },
  { id: 176, name: 'eritrea', iso: null },
  { id: 177, name: 'south sudan', iso: null },
  { id: 178, name: 'sao tome and principe', iso: null },
  { id: 179, name: 'aruba', iso: null },
  { id: 180, name: 'montserrat', iso: null },
  { id: 181, name: 'anguilla', iso: null },
  { id: 183, name: 'republic of north macedonia', iso: null },
  { id: 184, name: 'seychelles', iso: null },
  { id: 185, name: 'new caledonia', iso: 'US' },
  { id: 186, name: 'cape verde', iso: null },
  { id: 187, name: 'united states of america', iso: null },
  { id: 189, name: 'fiji', iso: null },
  { id: 196, name: 'singapore', iso: null },
  { id: 201, name: 'gibraltar', iso: null },
  { id: 203, name: 'kosovo', iso: null },
  { id: 204, name: 'niue', iso: null },
]

export const COUNTRY_BY_ID: ReadonlyMap<number, ProviderCountry> = new Map(
  PROVIDER_COUNTRIES.map((c) => [c.id, c]),
)

export const COUNTRY_BY_ISO: ReadonlyMap<string, ProviderCountry> = new Map(
  PROVIDER_COUNTRIES.filter((c) => c.iso).map((c) => [c.iso as string, c]),
)

/** Cameroon ID — confirmed via live SMS Online Pro getCountries on 2026-05-29 */
export const CAMEROON_ID = 41
